package fr.unedic.cali.autresdoms.ga.dom.spec;

public abstract interface ConstantesTypeParticulierContrat
{
  public static final int CONTRAT_TYPE_PARTICULIER_INDETERMINE = 0;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_APPRENTISSAGE_DOM = 1;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_APPRENTISSAGE_METROPOLE = 2;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_ADAPTATION = 3;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_ORIENTATION = 5;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_QUALIFICATION = 4;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_JEUNE = 6;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_CES = 7;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_CIF_SUITE_CDD = 8;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_LOCAL_ORIENTATION = 9;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_LOCAL_EMPLOI_JEUNE_1997 = 11;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_LOCAL_EMPLOI_JEUNE_EDUC_NAT = 10;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_UNIQUE_INSERTION_CAE = 23;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_UNIQUE_INSERTION_CIE = 24;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_NOUVELLE_EMBAUCHE = 12;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_ACCOMPAGNEMENT_EMPLOI = 14;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_INITIATIVE_EMPLOI = 15;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_AVENIR_RMI = 16;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_AVENIR_ASS_AVANT_JUIN_2009 = 21;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_AVENIR_ASS_APRES_JUIN_2009 = 211;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_INSERTION_RMA_RMI = 17;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_INSERTION_RMA_ASS_AVANT_JUIN_2009 = 22;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_INSERTION_RMA_ASS_APRES_JUIN_2009 = 221;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_JEUNE_ENTREPRISE = 18;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_PROFESSIONALISATION = 19;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_CEC = 20;
  public static final int CONTRAT_TYPE_PARTICULIER_CONTRAT_CEE = 30;
}

/* Location:
 * Qualified Name:     ConstantesTypeParticulierContrat
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */