package fr.unedic.cali.outilsfonctionnels;

public class BaseVisu
  extends AccesBase
{
  protected static final String NOM_TABLE_INDIVIDU = "P1297A_INDIVIDU";
  protected static final String NOM_TABLE_RAPPORT = "P1297B_RAPPORT";
  protected static final String NOM_TABLE_ELT_EXCLU = "P1297C_ELT_EXCLU";
  protected static final String NOM_TABLE_ELT_COMP = "P1297D_ELT_COMP";
  protected static final String NOM_TABLE_POPULATION = "P1297E_POPULATION";
  protected static final String NOM_TABLE_DEMANDE = "P1297F_DEMANDE";
  protected static final String NOM_TABLE_STATS = "P1297H_STATS_ANTEN";
  protected static final String NOM_TABLE_ECARTS = "P1297J_ECARTBASE";
  protected static final String NOM_TABLE_DELTAS_MT = "P1297K_DELTAMT";
  protected static final String COLONNE_RAPPORT_CXASS = "CXASS";
  protected static final String COLONNE_RAPPORT_FONCT_RAPP = "FONCT_RAPP_ID";
  protected static final String COLONNE_RAPPORT_LIB_RAPPORT = "LIB_RAPPORT";
  protected static final String COLONNE_RAPPORT_NOM_CHAINE = "NOM_CHAINE";
  protected static final String COLONNE_RAPPORT_MODE_OCCAS = "MODE_OCCAS";
  protected static final String COLONNE_RAPPORT_DATE_PASSAGE = "DATE_PASSAGE";
  protected static final String COLONNE_RAPPORT_NUM_PASSAGE = "NUM_PASSAGE";
  protected static final String COLONNE_INDIVIDU_CXASS = "CXASS";
  protected static final String COLONNE_INDIVIDU_CXALAF = "CXALAF";
  protected static final String COLONNE_INDIVIDU_CODE_POPULATION = "CODE_POPULATION";
  protected static final String COLONNE_INDIVIDU_FONCT_RAPP = "FK_FONCT_RAPP_ID";
  protected static final String COLONNE_DEMANDE_CXASS = "CXASS";
  protected static final String COLONNE_DEMANDE_CXALAF = "CXALAF";
  protected static final String COLONNE_DEMANDE_CODE_POPULATION = "CODE_POPULATION";
  protected static final String COLONNE_DEMANDE_FONCT_RAPP = "FK_FONCT_RAPP_ID";
  protected static final String COLONNE_DEMANDE_ID_DEMANDE = "DEMANDE_ID";
  protected static final String COLONNE_ELT_COMP_CXASS = "CXASS";
  protected static final String COLONNE_ELT_COMP_CXALAF = "CXALAF";
  protected static final String COLONNE_ELT_COMP_CODE_POPULATION = "CODE_POPULATION";
  protected static final String COLONNE_ELT_COMP_FONCT_RAPP = "FK_FONCT_RAPP_ID";
  protected static final String COLONNE_ELT_COMP_ID_DEMANDE = "FK_DEMANDE_ID";
  protected static final String COLONNE_ELT_COMP_NUM_ELEMENT = "NUM_ELEMENT";
  protected static final String COLONNES_RAPPORT = "CXASS,FONCT_RAPP_ID,LIB_RAPPORT,NOM_CHAINE,MODE_OCCAS,DATE_PASSAGE,NUM_PASSAGE,TSP";
  protected static final String COLONNES_INDIVIDU = "CXASS,FK_FONCT_RAPP_ID,CODE_POPULATION,CXALAF,RSIN,MODE_CREATION,DELTA_MT_BRUT,TSP,DATE_REEXECUTION, COD_ANT, ETAT_INDIVIDU, DELTA_MT_TRANCHE, DELTA_MT_CADT, DELTA_MT_CRC, DELTA_MT_FINAN, ETAT";
  protected static final String COLONNES_DEMANDE = "DEMANDE_ID,EST_IMPACTE,ETAT_REEXAM,EST_REEXECUTE,DATE_ATTRIB,CODE_PRODUIT,TYPE_DECIS,TYPE_DEMANDE,DELTA_PJI,DELTA_DJI,EST_MIGREE,EST_NEUTRALISEE,EST_FIGEE,TSP";
  protected static final String COLONNES_DEMANDE_INSERTION = "(CXASS,FK_FONCT_RAPP_ID,CODE_POPULATION,CXALAF,DEMANDE_ID,EST_DECIS,EST_IMPACTE,ETAT_REEXAM,EST_REEXECUTE,DATE_ATTRIB,CODE_PRODUIT,TYPE_DECIS,TYPE_DEMANDE,DELTA_PJI,DELTA_DJI,EST_MIGREE,EST_NEUTRALISEE,EST_FIGEE,TSP)";
  protected static final String NOM_COL_RAPPORT = "(CXASS,FONCT_RAPP_ID,LIB_RAPPORT,NOM_CHAINE,MODE_OCCAS,DATE_PASSAGE,NUM_PASSAGE,TSP)";
  protected static final String NOM_COL_INDIVIDU = "(CXASS,FK_FONCT_RAPP_ID,CODE_POPULATION,CXALAF,RSIN,MODE_CREATION,DELTA_MT_BRUT,TSP,DATE_REEXECUTION, COD_ANT, ETAT_INDIVIDU, DELTA_MT_TRANCHE, DELTA_MT_CADT, DELTA_MT_CRC, DELTA_MT_FINAN, ETAT)";
  protected static final String NOM_COL_POPULATION = "(CXASS,FK_FONCT_RAPP_ID,CODE_POPULATION,REEXAM_DEC_MIG,REEXEC_DEC_MIG,TYPE_MANDATEMENT,APPLI_PREM_DEC,LIB_POPULATION,TSP,CONSIGNE_1,CONSIGNE_2,CONSIGNE_3)";
  protected static final String NOM_COL_ELT_EXCLU = "(CXASS,FK_FONCT_RAPP_ID,CODE_POPULATION,CODE_GAMME,CODE_PRODUIT,NUM_ELEMENT,TSP)";
  protected static final String NOM_COL_DEMANDE = "(DEMANDE_ID,EST_IMPACTE,ETAT_REEXAM,EST_REEXECUTE,DATE_ATTRIB,CODE_PRODUIT,TYPE_DECIS,TYPE_DEMANDE,DELTA_PJI,DELTA_DJI,EST_MIGREE,EST_NEUTRALISEE,EST_FIGEE,TSP)";
  protected static final String NOM_COL_ELT_COMP = "(CXASS,FK_FONCT_RAPP_ID,CODE_POPULATION,CXALAF,FK_DEMANDE_ID,NUM_ELEMENT,VALEUR_AVANT,VALEUR_APRES,TSP,LIB_ELEMENT)";
  protected static final String ERR_OCCAS_PARAM_NULL = "ERR_OCCAS_PARAM_NULL";
}

/* Location:
 * Qualified Name:     BaseVisu
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */